2021-09-05 23:30:21.342 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - Error al armar cliente en la linea
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:64) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:30) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2021-09-05 23:33:54.598 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - Error al armar cliente en la linea
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:62) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:30) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2021-09-05 23:34:07.244 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - Error al armar cliente en la linea
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:62) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:30) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2021-09-05 23:35:00.694 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - Error al armar cliente en la linea
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCliente(AdminClientes.java:62) [classes/:?]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:30) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestArchivoCorrupto.testLeer(TestArchivoCorrupto.java:13) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2021-09-06 03:00:00.898 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No existe el archivo en la ruta: 
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes1.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_281]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_281]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_281]
	at java.io.FileReader.<init>(FileReader.java:72) ~[?:1.8.0_281]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:27) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteA(TestColocarPrestamos.java:21) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
2021-09-06 03:00:00.909 [main] ERROR com.cmc.evaluacion.fase2.servicios.AdminClientes - No existe el archivo en la ruta: 
java.io.FileNotFoundException: C:\Users\AdminCMC\Downloads\Clientes1.txt (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_281]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_281]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_281]
	at java.io.FileReader.<init>(FileReader.java:72) ~[?:1.8.0_281]
	at com.cmc.evaluacion.fase2.servicios.AdminClientes.armarCartera(AdminClientes.java:27) [classes/:?]
	at com.cmc.evaluacion.fase2.test.TestColocarPrestamos.testColocarClienteB(TestColocarPrestamos.java:32) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at junit.framework.TestCase.runTest(TestCase.java:154) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.runBare(TestCase.java:127) [junit-3.8.1.jar:?]
	at junit.framework.TestResult$1.protect(TestResult.java:106) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.runProtected(TestResult.java:124) [junit-3.8.1.jar:?]
	at junit.framework.TestResult.run(TestResult.java:109) [junit-3.8.1.jar:?]
	at junit.framework.TestCase.run(TestCase.java:118) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.runTest(TestSuite.java:208) [junit-3.8.1.jar:?]
	at junit.framework.TestSuite.run(TestSuite.java:203) [junit-3.8.1.jar:?]
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192) [.cp/:?]
